version: "3.7"

services:
  cg-edge-conf-api:
    image: cadugrillo/vessl:0.2
    container_name: vessl
    restart: always
    mem_limit: 128m
    cpus: 0.5
    volumes:
      - vessl-database:/database
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind                          #When Linux Host integration is in use
        source: /etc/network                #When Linux Host integration is in use
        target: /etc/network                #When Linux Host integration is in use
    extra_hosts:                            #When Linux Host integration is in use
      - "host.docker.internal:host-gateway" #When Linux Host integration is in use
    networks:
      - vessl-default
    ports:
      - 443:443

networks:
   vessl-default:
      name: vessl-default

volumes:
  vessl-database:
    name: vessl-database