version: "3.7"

services:
  cg-edge-conf-api:
    image: cadugrillo/vessl:1.1
    container_name: vessl
    restart: always
    mem_limit: 256m
    cpus: 0.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - vessl-database:/database
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/network
        target: /etc/network
      - type: bind
        source: /home/edge/apps
        target: /apps
    networks:
      - vessl-default
    ports:
      - 443:443

networks:
   vessl-default:
      name: vessl-default

volumes:
  vessl-database:
    name: vessl-database