clientSub:
    clientId: cg_subscriberItworks
    serverAddress: tcp://datalake:1883
    qos: 2
    connectionTimeout: 1
    writeTimeout: 1
    keepAlive: 30
    pingTimeout: 1
    connectRetry: true
    autoConnect: true
    orderMaters: false
    userName: rw
    password: readwrite
    tlsConn: false
    rootCAPath: ./certs/sub/xxxxxxxx
    clientKeyPath: ./certs/sub/xxxxxxxx
    privateKeyPath: ./certs/sub/xxxxxxxx
    insecureSkipVerify: true
clientPub:
    clientId: cg_publisher
    serverAddress: tcps://a3lnu97tk1lj18-ats.iot.us-east-1.amazonaws.com:8883/mqtt
    qos: 0
    connectionTimeout: 1
    writeTimeout: 1
    keepAlive: 30
    pingTimeout: 1
    connectRetry: true
    autoConnect: true
    orderMaters: false
    userName: ""
    password: ""
    tlsConn: true
    rootCAPath: ./certs/pub/AmazonRootCA1.pem
    clientKeyPath: ./certs/pub/b4aa6501aafb00f805d710111d59ef07ee19e8affc6997a1a5c187b868b7aa0b-certificate.pem.crt
    privateKeyPath: ./certs/pub/b4aa6501aafb00f805d710111d59ef07ee19e8affc6997a1a5c187b868b7aa0b-private.pem.key
    insecureSkipVerify: true
    translateTopic: false
    publishInterval: 250
logs:
    subPayload: true
    debug: false
    warning: false
    error: false
    critical: false
topicsSub:
    topic:
        - cg-connector/sample/1
        - cg-connector/sample/2
        - cg-connector/sample/3
topicsPub:
    topic:
        - cg-connector/sample/21
        - cg-connector/sample/22
        - cg-connector/sample/33
