#stage 1
FROM node:latest as node
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --force
COPY . .
RUN npm install -g @angular/cli
RUN ng build --output-path=/dist

#stage 2
FROM nginx:alpine
COPY --from=node /dist /usr/share/nginx/html
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY ./ssl/cg-edge.crt /etc/ssl/certs/
COPY ./ssl/cg-edge.key /etc/ssl/private/
EXPOSE 80
EXPOSE 443